#Should the indicator be shown to everyone(true) or just the damager(false)
ShowToDamagerOnly: true

#The format for showing the damage (example: "&7-0.0#&4❤")
#https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html
IndicatorFormat: "&7-0.#&4❤"
CriticalIndicatorFormat: "&c-0.#&4❤"
