name: 'DamageIndicator'
version: '${version}'
main: com.github.magiccheese1.damageindicator.Main
api-version: 1.16
commands:
  damageindicator:
    description: Reload
    permission: Damageindicator.admin
